package com.creativegrpcx.perawatcher.ui.theme
import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF56633E)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFD9E8BA)
val md_theme_light_onPrimaryContainer = Color(0xFF141F03)
val md_theme_light_secondary = Color(0xFF5D6054)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFE2E4D5)
val md_theme_light_onSecondaryContainer = Color(0xFF1A1D14)
val md_theme_light_tertiary = Color(0xFF52625F)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFD5E6E3)
val md_theme_light_onTertiaryContainer = Color(0xFF0F1E1C)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFCF8)
val md_theme_light_onBackground = Color(0xFF1C1C1A)
val md_theme_light_surface = Color(0xFFFFFCF8)
val md_theme_light_onSurface = Color(0xFF1C1C1A)
val md_theme_light_surfaceVariant = Color(0xFFE4E3DB)
val md_theme_light_onSurfaceVariant = Color(0xFF464742)
val md_theme_light_outline = Color(0xFF777772)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_inverseSurface = Color(0xFF31302E)
val md_theme_light_inverseOnSurface = Color(0xFFF3F0EC)
val md_theme_light_inversePrimary = Color(0xFFBDCCA0)
val md_theme_light_surfaceTint = Color(0xFF56633E)

val md_theme_dark_primary = Color(0xFFBDCCA0)
val md_theme_dark_onPrimary = Color(0xFF293414)
val md_theme_dark_primaryContainer = Color(0xFF3F4B29)
val md_theme_dark_onPrimaryContainer = Color(0xFFD9E8BA)
val md_theme_dark_secondary = Color(0xFFC6C8BA)
val md_theme_dark_onSecondary = Color(0xFF2F3228)
val md_theme_dark_secondaryContainer = Color(0xFF45483D)
val md_theme_dark_onSecondaryContainer = Color(0xFFE2E4D5)
val md_theme_dark_tertiary = Color(0xFFB9CAC7)
val md_theme_dark_onTertiary = Color(0xFF243331)
val md_theme_dark_tertiaryContainer = Color(0xFF3A4A48)
val md_theme_dark_onTertiaryContainer = Color(0xFFD5E6E3)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onErrorContainer = Color(0xFFFFB4AB)
val md_theme_dark_background = Color(0xFF1C1C1A)
val md_theme_dark_onBackground = Color(0xFFE5E2DE)
val md_theme_dark_surface = Color(0xFF1C1C1A)
val md_theme_dark_onSurface = Color(0xFFE5E2DE)
val md_theme_dark_surfaceVariant = Color(0xFF464742)
val md_theme_dark_onSurfaceVariant = Color(0xFFC7C7C0)
val md_theme_dark_outline = Color(0xFF91918B)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_inverseSurface = Color(0xFFE5E2DE)
val md_theme_dark_inverseOnSurface = Color(0xFF31302E)
val md_theme_dark_inversePrimary = Color(0xFF56633E)
val md_theme_dark_surfaceTint = Color(0xFFBDCCA0)


val seed = Color(0xFF7D8B63)
